apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: quarkus-mar3-1
  janus-idp.io/tekton: quarkus-mar3-1
  backstage.io/kubernetes-id: quarkus-mar3-1
  backstage.io/kubernetes-namespace: quarkus-mar3-1
  app.kubernetes.io/part-of: quarkus-mar3-1
resources:
  - initialize-namespace.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
